---
- name: Set common variables
  set_fact:
    pihole_config_path: /etc/pihole

- name: "Download Pi-Hole installer"
  get_url:
    url: https://install.pi-hole.net
    dest: ~/install-pihole.sh
    mode: 0740

- name: Create pihole configuration directory
  file:
    name="{{ pihole_config_path }}"
    state=directory
    mode=0775

- name: Create pihole configuration
  template:
    src="setupVars.conf.j2"
    dest="{{ pihole_config_path }}/setupVars.conf"
    owner=root
    group=root
    mode=0644

- name: Install Pi-Hole
  command: /root/install-pihole.sh --unattended
  register: rst_install_pihole

- name: Set Pi-hole admin console password
  command: "pihole -a -p {{ pihole_admin_console_password }}"

# TODO: update pihole regularly
